### ISSUE TITLE
Questions, Nyame R20, TP Range etc.

### ISSUE THREAD

**Issue by bjggi** [IzaKastra/wsdist#1]
Really great work!

I have a few questions about this:

1.) Would it be possible to implement e.g. Nyame R20 etc., and Blurred Shield?
2.) How do I find the best TP Range Min. Max. for WS? For ex. Torcleaver, do i set it to 1000-1250? Or is there a way to find the best threshold? I was always interested if i should hold TP to a certain range on some WS's.
3.) Are you planning to add more jobs, SAM, WAR, DRG, MNK, BRD, COR etc. or subjob /DRG

If you need help, items or stats (i have almost all jobs @ML 40+) I'm happy to help. I dont think i can wrap my head around this pull github stuff, but i can gladly get u a list, lets say all sam gear, in a format like u did in gear.py, if this helps.

**Comment by IzaKastra** [comment]
I've pushed an updated version of the code which I describe on the latest ffxiah post https://www.ffxiah.com/forum/topic/56125/using-python3-to-estimate-bis-gear-sets-for-ninja/4/#3648847

1. You can add lower-ranked Odyssey gear to the gear.py file if you want to test them in the code. I may add them myself later, but I'll have to find a way to avoid checking all versions of the same item or the code's runtime could be large. I've added Blurred Shield +1 (and Fencer traits) with the most recent update today.

2. To find the best TP value to use a weapon skill at, you just look at the FTP values at different TP ranges (BG Wiki has the full list). For the range I use in the code: I usually just pick lower_limit=best_value and upper_limit=best_value+300TP to account for TP overflow (in game you never WS at exactly 1000 TP, it's always a bit higher).

For example. Torcleaver has FTP=[4.75, 7.5, 9.765625] at [1000,2000,3000] TP. The FTP is a damage multiplier so 1000 TP is x4.75 damage. If you DOUBLE your TP to 2000, then your multiplier jumps to 7.5 which is only 7.5/4.75=1.57 times more damage than if you went at 1000. This means you wait twice as long to get 2000 TP but only gain 57% more damage. This means it isn't efficient to hold TP over 1000 for Torcleaver.

However, if you look at Savage Blade: the FTP is [4.0, 10.25, 13.75] at [1000, 2000, 3000] TP. So WSing at 1000 is only x4.0 damage, while doubling TP to 2000 gives x10.25 damage, which is a x2.6 damage increase over spamming at 1000. In this case you wait twice as long to get 2000 TP, but you get 160% more damage from it. This means it's best to wait until 2000 TP to use Savage Blade.

Finally, there are weapon skills that don't change their FTP. Look at Relic weaponskills, Blade: Metsu for example has FTP=5.0 at all TP values. Aftermath duration changes with TP, but damage does not. This means you will gain no extra damage for holding TP, so you should just weaponskill immediately.

3. I've mostly added DRG, SAM, and RDM today, as well as /DRG and others using NIN base stats (STR, DEX, VIT, AGI, INT, MND, CHR) since I can't log on to check these myself until January at the earliest.

If you can provide Lv99 (or ML+) base stats for a job, then I can add it to the code pretty easily. I specifically need stats without a subjob. You can remove your subjob in game by setting your subjob to something, then setting your main job to the same thing as the server updates your subjob. This is difficult to time correctly, but it can be done after a few attempts. I usually require a dozen or so attempts and have to wait about 0.5~1.0 second to set my main job for it to work.

Additionally, I could use Lv53 subjob stats. Essentially just take off your subjob at ML20-24, check your stats, then set a subjob and see how the stats changed.

I imagine I will not add a lot of gear for many other jobs anytime soon. Adding gear in the correct format is tedious. If you want to provide the gear in the correct format, then I'll be happy to include it so we can start checking things like COR, BRD, etc. I have some of the SAM gear added already (some JSE and stuff it shares with NIN and DRK), but feel free to send me more if you want it added. Be sure to check the gear.py file to be sure I haven't already included the gear, though.
