### ISSUE TITLE
Suggestion for project requirements

### ISSUE THREAD

**Issue by kanusek** [IzaKastra/wsdist#11]
I'm retired from FFXI but a friend told me about your project. They asked me to see if I could add a feature to save a set of gear.
You've made a cool program and I wish I had enough time to contribute to it.

One suggestion I have is to add a requirements.txt file that pins packages used in your project.  As well as state somewhere in your readme which version of python you developed this with. For example, numba doesn't work with python 3.11 but it's happy with 3.10.

Here's what `pip freeze` returned after I installed the packages you listed: 

```
contourpy==1.0.7
cycler==0.11.0
fonttools==4.39.2
kiwisolver==1.4.4
llvmlite==0.39.1
matplotlib==3.7.1
numba==0.56.4
numpy==1.23.5
packaging==23.0
Pillow==9.4.0
pyparsing==3.0.9
PySimpleGUI==4.60.4
python-dateutil==2.8.2
six==1.16.0
wincertstore==0.2
```

Cheers

**Comment by IzaKastra** [comment]
Thanks for the suggestion. I've added requirements files based on what I see using `pip freeze` on my computer. The Python version used to develop/compile the code is listed in the README file as Python3.8.8.

As for saving gear sets: it depends on what that means. Writing the equipped gear to a text file in a specific format would be very easy to do. However, importing that gear back into the code would, at the very least, be annoying to do because most of the code is not well written. The easiest way I can think to equip a gear set based on an input file is to loop over all possible gear in each slot and equip the pieces that match what the input file has listed. This could probably be done rather quickly with list comprehension, actually.

**Comment by kanusek** [comment]
I missed the python version in the readme, very good.
The request as it came to me was: 
```
it does all gear, and you cant save it once you have added your gear, 
or better yet, it doesnt take into account the gear you have
which can be found it other outputs from the game 
- like findall or gs export (i like findall because its constantly updating )
i just dont know how to integrate that filter into the list
```

I explained to them that this is an offline program and isn't getting data from the running game. 
I think you're right that saving the current set of gear to a file is the easiest solution. 
When I was checking it out, I was wondering if you could use adapt the 'Copy best set' process to handle this.

Later on I realized that if some one is using your program they're probably also using gearswap. So I got a friend to send me their gearswap lua files and I spent a couple hours trying to parse them with python. I tried luaparser and was able to parse the file but the library makes it very difficult to get values from what I saw. I might have another go at it if I have time.
