### ISSUE TITLE
weapon not adding

### ISSUE THREAD

**Issue by maxlink89** [IzaKastra/wsdist#13]
tryed to add a weapon to the list but it not appering in the app was woundering if i missed a step somewhere

Raetic_staff = {"Name":"Raetic Staff +1","NAme2":"Raetic Staff +1","HP":40,"MP":40,"Magic Accuracy":62,"Magic Attack":31,"Magic Damage":217,"Staff Skill":215,"Parrying Skill":215,"Magic Accuracy Skill":242,"Elemental Magic MP Consumed":30,"Magic Damage":50,"Magic Attack":50,"skill type": "Staff","type":"Weapon","DMG":245,"Delay":365,"jobs":["war","mnk","whm","blm","rdm","bst","brd","smn","sch","geo"]}

is what i added following the other stuff that was already added

**Comment by IzaKastra** [comment]
After you create the weapon dictionary (which is what you posted already), you need to add it to the "mains" list (on line 259 of the current version of the gear.py code) for the code to recognize it. So your "mains" list will look something like 

`mains = [Raetic_staff, Jugo_Kukri, Demersal_Degen, Comeuppances, Aettir, . . .]`


After you've added it to the "mains" list, you will have to recompile the code if you're using the gui_wsdist.exe version, otherwise it won't update. If you're using the gui_wsdist.py version of the code, then you won't have to compile anything and it should work immediately after making the changes to the file.


Additionally, the code does not use all stats, and the stats used by the code are case-sensitive. In your Raetic_staff example you'll need to:

1. Rename "NAme2" to "Name2"
2. Remove the HP and MP stats
3. Remove the "Parrying Skill" stat
4. Remove the "Elemental Magic MP Consumed" stat
5. Rename "skill type" to "Skill Type"
6. Consolidate your multiple "Magic Attack" and "Magic Damage" stats into one stat for each.
7. Rename "jobs" to "Jobs"
8. Rename "type" to "Type"
