### ISSUE TITLE
Missing Sam Gear

### ISSUE THREAD

**Issue by bjggi** [IzaKastra/wsdist#2]
Would it be possibel to add some SAM Gear. I guess vor Jinpu the Back Mag.Acc.Dmg should be ahead?

```
Smertrios_MAGIC = { name="Smertrios's Mantle", augments={'STR+20','Mag. Acc+20 /Mag. Dmg.+20','Magic Damage +10','Weapon skill damage +10%','Phys. dmg. taken-10%',}}

Kasuga_Kote = {"Name": "Kasuga Kote +3", "STR":24,"DEX":47,"VIT":47,"AGI":23,"INT":21,"MND":38,"CHR":31,"Gear Haste":4,"Accuracy":62,"Attack":62,"Magic Accuracy":62,"Weaponskill Damage":12, "Jobs":["sam"]}
Kasuga_Sune_Ate = {"Name":"Kasuga Sune-Ate +3", "STR":31,"DEX":34,"VIT":31,"AGI":40,"MND":20,"CHR":34,"Accuracy":60,"Attack":70,"Magic Accuracy":60,"Gear Haste":3,"PDL":10,"Jobs":["sam"]}
```
The Kasuga Feet also has  "Conserve TP"+14, not sure how this comes to play then for the TP Set :) 

I will have more Time next week, i will try to get u more Gear and maybe Base stats on Jobs.

Thx again for ur great work!

**Comment by bjggi** [comment]
A Question, would Sheol Gaol work too for the Base Stats? For whatever Reasons, i cant hit the timing to remove the Subjob.

**Comment by IzaKastra** [comment]
Yes, Odyssey Gaol would work. I completely forgot that Gaol removes subjob before you enter fights.

I have NIN DRK BLM SCH and /RDM /SCH /WAR and /DRK(I think) correct now, but I still need others.

I shouldn't need any more gear. I wrote a simple Python code that lets me copy/paste BG Wiki format and get gear in my code's format. I just need to manually delete a few spaces in the BG format first, but it's only a few seconds per piece of gear now. I have added a ton of new gear because of this. I'll go ahead and close this issue as well since the gear is mostly added now. You can re-open it if you find gear I missed.

Part of the new gear.py file includes loop that creates A LOT of ambu capes with different stat combinations (and another part creates a few Linos for melee BRD). I'm about to push another update that includes SAM STR+WSD+Macc/Mdmg. Many other jobs already had these combinations, though.

TP sets are actually still a while away. I have the code for it from forever ago when I found NIN TP sets, but I never want to sit down and add it to the GUI. It's more fun to add new jobs instead.

The current version of the code includes support for:
NIN DRK BLM SCH DRG* SAM* WAR* WHM* RDM* COR* BRD*

with the subjobs:
/53rdm /53sch /53sam /53drk /53war /53drg* /53nin*

but the jobs above with stars need corrected base stats.

I've added most gear for most of these jobs too, but I only play NIN WHM and DRK so I may have missed a few pieces. Additionally, some pieces of gear that were added when NIN was the only job included might not have all jobs listed properly yet.

The code also includes Magic and Ranged WSs, helix spells, and quick draw now.



I'll probably make a post about this update on ffxiah tomorrow.

**Comment by bjggi** [comment]
Here are some Base Stats from Gaol. If u need more or something is off, feel free to respond.

--- SAM lvl 99 (Master lvl50) Hume

'STR':143,
'DEX':143, 
'VIT':143, 
'AGI':140, 
'INT':137, 
'MND':137, 
'CHR':140,


--- WHM lvl 99 (no Master) Hume

'STR':90,
'DEX':84, 
'VIT':90, 
'AGI':87, 
'INT':87, 
'MND':97, 
'CHR':93,


--- RDM lvl 99 (no Master) Hume

'STR':90,
'DEX':90, 
'VIT':87, 
'AGI':87, 
'INT':93, 
'MND':93, 
'CHR':90,


--- DRG lvl 99 (Master lvl40) Hume

'STR':135,
'DEX':130, 
'VIT':133, 
'AGI':130, 
'INT':124, 
'MND':127, 
'CHR':133,


--- WAR lvl 99 (no Master) Hume

'STR':97,
'DEX':93, 
'VIT':90, 
'AGI':93, 
'INT':84, 
'MND':84, 
'CHR':87,


--- COR lvl 99  (no Master) Hume

'STR':87,
'DEX':93, 
'VIT':87, 
'AGI':95, 
'INT':93, 
'MND':87, 
'CHR':87,


--- BRD lvl 99 (no Master) Hume

'STR':90,
'DEX':90, 
'VIT':90, 
'AGI':84, 
'INT':90, 
'MND':90, 
'CHR':95,


--- BLU lvl 99  (no Master) Hume

'STR':87,
'DEX':87, 
'VIT':87, 
'AGI':87, 
'INT':87, 
'MND':87, 
'CHR':87,


--- MNK lvl 99  (Master lvl40) Hume

'STR':133,
'DEX':135, 
'VIT':137, 
'AGI':124, 
'INT':121, 
'MND':130, 
'CHR':127,


--- THF lvl 99  (no Master) Hume

'STR':90,
'DEX':97, 
'VIT':90, 
'AGI':95, 
'INT':93, 
'MND':81, 
'CHR':81,
